spring:
  datasource:
    url: ${DEV_MYSQL_URL}
    username: ${DEV_MYSQL_USERNAME}
    password: ${DEV_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${AWS_ELASITCACHE_REDIS_URL}
      port: ${AWS_ELASITCACHE_REDIS_PORT}

    mongodb:
      uri: ${ATLAS_MONGO_URI}
      database: ${ATLAS_MONGO_DATABASE}

cloud:
  aws:
    rds:
      database:
        url: ${AWS_RDS_MYSQL_URL}
        port: ${AWS_RDS_MYSQL_PORT}

ssh:
  host: ${SSH_HOST}
  port: ${SSH_PORT}
  user: ${SSH_USER}
  private_key_path: ${SSH_PRIVATE_KEY_PATH}

jwt:
  access:
    secret: ${DEV_JWT_ACCESS_SECRET}
    expire: ${DEV_JWT_ACCESS_EXPIRE}

  refresh:
    secret: ${DEV_JWT_REFRESH_SECRET}
    expire: ${DEV_JWT_REFRESH_EXPIRE}
    ttl:
      seconds: ${DEV_JWT_REFRESH_TTL_SECONDS}
